"""adicionar_campo_caucao

Revision ID: 4383e014f283
Revises: cee049dfe786
Create Date: 2025-07-08 20:40:56.131386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4383e014f283'
down_revision = 'cee049dfe786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_caucao', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('valor_caucao')

    # ### end Alembic commands ###
