"""Adicionar tabela de boletos

Revision ID: 86248b5a7c3a
Revises: bb09ace6eb18
Create Date: 2025-07-05 20:30:59.937706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86248b5a7c3a'
down_revision = 'bb09ace6eb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boleto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('valor_aluguel', sa.Float(), nullable=False),
    sa.Column('valor_condominio', sa.Float(), nullable=True),
    sa.Column('valor_iptu', sa.Float(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('link_boleto', sa.String(length=500), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_unidade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_unidade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('local_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'livre'"), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['local.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'local_id', name=op.f('uq_unidade_nome_local'))
    )
    op.drop_table('boleto')
    # ### end Alembic commands ###
