"""Adicionar campo arquivo_contrato

Revision ID: 8c8f581c33ab
Revises: 86248b5a7c3a
Create Date: 2025-07-05 20:38:06.232738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8f581c33ab'
down_revision = '86248b5a7c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo_contrato', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('arquivo_contrato')

    # ### end Alembic commands ###
