"""adicionar_campos_assinatura_digital

Revision ID: 8e595173857c
Revises: 8c8f581c33ab
Create Date: 2025-07-05 22:44:26.968692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e595173857c'
down_revision = '8c8f581c33ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envelope_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_assinatura', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('arquivo_contrato_assinado', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('data_envio_assinatura', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_assinatura', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('data_assinatura')
        batch_op.drop_column('data_envio_assinatura')
        batch_op.drop_column('arquivo_contrato_assinado')
        batch_op.drop_column('status_assinatura')
        batch_op.drop_column('envelope_id')

    # ### end Alembic commands ###
