"""adicionar_campos_login_inquilino

Revision ID: cee049dfe786
Revises: 8e595173857c
Create Date: 2025-07-06 01:27:43.484196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee049dfe786'
down_revision = '8e595173857c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquilino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_criacao_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_login', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_inquilino_username', ['username'])

    # Atualizar registros existentes para status_login='inativo'
    op.execute("UPDATE inquilino SET status_login='inativo' WHERE status_login IS NULL")

    # Alterar para NOT NULL
    with op.batch_alter_table('inquilino', schema=None) as batch_op:
        batch_op.alter_column('status_login', existing_type=sa.String(length=20), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquilino', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inquilino_username', type_='unique')
        batch_op.drop_column('status_login')
        batch_op.drop_column('data_criacao_login')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
